-- seed_data.sql

-- Users
INSERT INTO User (email, user_name, password, first_name, last_name, display_name, avatar, is_active, role, bio)
VALUES
    ('estecat@yahoo.com', 'estecat', '$2a$10$/M7/19bq2SR7G9Dqf2/1t.vVEM22y86TDUci71FO/3O1wLi2/p7Ty', 'Esteban', 'Price', 'Bubba', 'este-profile.jpg', 0, 1, 
     '🐈‍⬛ dad Im hungry wheres dinner'),

    ('whispers_from_wallphace@gmail.com', 'wallphace', '$2a$10$/M7/19bq2SR7G9Dqf2/1t.vVEM22y86TDUci71FO/3O1wLi2/p7Ty', 'Marcus', 'Price', 'Whispers From Wallphace', 'wallphace-profile.jpg', 0, 2, 
     'A dad shotgunning a blunt in his son’s mouth before school'),

    ('d.cooper@fbi.gov', 'dalecooper', '$2a$10$/M7/19bq2SR7G9Dqf2/1t.vVEM22y86TDUci71FO/3O1wLi2/p7Ty', 'Dale', 'Cooper', 'Special Agent Dale Cooper', 'cooper-profile.png', 0, 3,
     'FBI Special Agent investigating the mysteries of Twin Peaks. I follow intuition, trust dreams, and never start a day without a damn fine cup of coffee.'),

    ('audrey@hornesdepartmentstore.com', 'audrey', '$2a$10$/M7/19bq2SR7G9Dqf2/1t.vVEM22y86TDUci71FO/3O1wLi2/p7Ty', 'Audrey', 'Horne', 'Audrey', 'audrey-profile.jpg', 0, 1,
     'People underestimate me, but I always find my way in. Curious, clever, and not afraid to stir up trouble—especially when something doesn’t add up.'),

    ('bobby.briggs@twinpeakswa.gov', 'bobbybriggs', '$2a$10$/M7/19bq2SR7G9Dqf2/1t.vVEM22y86TDUci71FO/3O1wLi2/p7Ty', 'Bobby', 'Briggs', 'Bobby', 'bobby-profile.jpeg', 0, 1,
     'Used to be the golden boy, now I''m trying to figure out who I really am. Life''s messy, love’s messier, and Twin Peaks doesn’t make it any easier.'),

    ('donna.hayward@twinpeaksclinic.com', 'donnahayward', '$2a$10$/M7/19bq2SR7G9Dqf2/1t.vVEM22y86TDUci71FO/3O1wLi2/p7Ty', 'Donna', 'Hayward', 'Donna', 'donna-profile.jpg', 0, 1,
     'I just want the truth. About Laura, about this town, about everything. I’ll keep asking questions, even if I don’t like the answers.'),

    ('marcusprice88@gmail.com', 'endlesshappiness', '$2a$10$/M7/19bq2SR7G9Dqf2/1t.vVEM22y86TDUci71FO/3O1wLi2/p7Ty', 'Marcus', 'Price', 'Eternal Freeskate', 'marcus-profile.jpg', 0, 1, 
     '👽');


-- Posts (assumes the above inserts generate ids 1–6 in the same order)
INSERT INTO Post (user_id, content, image, created_at, updated_at) VALUES
    (3, 'Diane! I''m holding in my hand a small box of chocolate bunnies.', 'chocolate-bunnies.png', datetime(current_timestamp, '-4 days', '+1 hours', '+20 minutes'), datetime(current_timestamp, '-4 days', '+1 hours', '+192 minutes')),
    (2, 'Esteban knocked over the plant again. 3rd time this week.', '', datetime(current_timestamp, '-22 days', '+14 hours', '+13 minutes'), datetime(current_timestamp, '-22 days', '+14 hours', '+114 minutes')),
    (2, '', 'modular_patch.png', datetime(current_timestamp, '-30 days', '+11 hours', '+1 minutes'), datetime(current_timestamp, '-30 days', '+11 hours', '+1 minutes')),
    (3, 'Nothing beats a damn fine cup of coffee in the morning.', 'double-r-diner.jpg', datetime(current_timestamp, '-23 days', '+6 hours', '+46 minutes'), datetime(current_timestamp, '-23 days', '+6 hours', '+46 minutes')),
    (4, 'High school sucks. At least I’ve got my bike.', '', datetime(current_timestamp, '-22 days', '+18 hours', '+28 minutes'), datetime(current_timestamp, '-22 days', '+18 hours', '+28 minutes')),
    (5, 'Sometimes I think I can still hear her... Laura.', 'laura-locket.jpg', datetime(current_timestamp, '-6 days', '+2 hours', '+44 minutes'), datetime(current_timestamp, '-6 days', '+2 hours', '+75 minutes')),
    (2, 'Recording whispers again tonight. Got a new contact mic.', '', datetime(current_timestamp, '-17 days', '+17 hours', '+4 minutes'), datetime(current_timestamp, '-17 days', '+17 hours', '+4 minutes')),
    (1, '', 'esteban-snoozing.jpg', datetime(current_timestamp, '-29 days', '+10 hours', '+39 minutes'), datetime(current_timestamp, '-29 days', '+10 hours', '+39 minutes')),
    (5, 'The woods have secrets. I’m starting to believe it now.', '', datetime(current_timestamp, '-27 days', '+20 hours', '+24 minutes'), datetime(current_timestamp, '-27 days', '+20 hours', '+123 minutes')),
    (4, 'Cruised past the sheriff''s station. Coop’s still parked outside.', 'bobby-bike.jpg', datetime(current_timestamp, '-7 days', '+22 hours', '+50 minutes'), datetime(current_timestamp, '-7 days', '+22 hours', '+50 minutes')),
    (6, 'Dreamt of the Black Lodge again. So vivid.', '', datetime(current_timestamp, '-22 days', '+17 hours', '+59 minutes'), datetime(current_timestamp, '-22 days', '+17 hours', '+125 minutes')),
    (2, '', 'modular-mess.jpg', datetime(current_timestamp, '-29 days', '+12 hours', '+11 minutes'), datetime(current_timestamp, '-29 days', '+12 hours', '+11 minutes')),
    (3, 'Cherry pie and case files. Standard Tuesday.', '', datetime(current_timestamp, '-23 days', '+0 hours', '+39 minutes'), datetime(current_timestamp, '-23 days', '+0 hours', '+39 minutes')),
    (1, 'Esteban tried to climb into the sink again.', 'esteban-sink.png', datetime(current_timestamp, '-11 days', '+0 hours', '+21 minutes'), datetime(current_timestamp, '-11 days', '+0 hours', '+21 minutes')),
    (5, 'Lights flickering again. Something’s wrong.', '', datetime(current_timestamp, '-19 days', '+5 hours', '+33 minutes'), datetime(current_timestamp, '-19 days', '+5 hours', '+33 minutes')),
    (4, 'Felt like someone was watching me in the woods.', 'woods-shadow.jpg', datetime(current_timestamp, '-14 days', '+3 hours', '+7 minutes'), datetime(current_timestamp, '-14 days', '+3 hours', '+7 minutes')),
    (2, 'Built a delay feedback loop. Sounds like ghosts.', '', datetime(current_timestamp, '-27 days', '+16 hours', '+41 minutes'), datetime(current_timestamp, '-27 days', '+16 hours', '+41 minutes')),
    (3, '', 'log-lady.jpg', datetime(current_timestamp, '-4 days', '+2 hours', '+13 minutes'), datetime(current_timestamp, '-4 days', '+2 hours', '+13 minutes')),
    (6, 'Donna’s mix tape is fire. Forgot she liked shoegaze.', '', datetime(current_timestamp, '-11 days', '+2 hours', '+0 minutes'), datetime(current_timestamp, '-11 days', '+2 hours', '+166 minutes')),
    (4, '', 'bike-trails.jpg', datetime(current_timestamp, '-13 days', '+23 hours', '+26 minutes'), datetime(current_timestamp, '-13 days', '+23 hours', '+26 minutes')),
    (5, 'Heard a howl last night that wasn’t a coyote.', '', datetime(current_timestamp, '-9 days', '+13 hours', '+40 minutes'), datetime(current_timestamp, '-9 days', '+13 hours', '+181 minutes')),
    (2, 'New patch idea: granular + FM + reverse reverb.', '', datetime(current_timestamp, '-9 days', '+22 hours', '+35 minutes'), datetime(current_timestamp, '-9 days', '+22 hours', '+35 minutes')),
    (1, '', 'esteban-window.jpg', datetime(current_timestamp, '-7 days', '+9 hours', '+35 minutes'), datetime(current_timestamp, '-7 days', '+9 hours', '+78 minutes')),
    (3, 'Agent Rosenfield’s jokes are getting worse.', '', datetime(current_timestamp, '-24 days', '+12 hours', '+2 minutes'), datetime(current_timestamp, '-24 days', '+12 hours', '+2 minutes')),
    (6, '', 'clinic-lights.jpg', datetime(current_timestamp, '-21 days', '+8 hours', '+42 minutes'), datetime(current_timestamp, '-21 days', '+8 hours', '+207 minutes')),
    (2, 'Woke up and all my gear was patched and powered. Didn’t touch it.', '', datetime(current_timestamp, '-6 days', '+16 hours', '+7 minutes'), datetime(current_timestamp, '-6 days', '+16 hours', '+140 minutes')),
    (1, '', 'cat-midair.jpg', datetime(current_timestamp, '-2 days', '+6 hours', '+39 minutes'), datetime(current_timestamp, '-2 days', '+6 hours', '+39 minutes')),
    (4, 'Audrey said something strange today. She seemed... distant.', '', datetime(current_timestamp, '-14 days', '+8 hours', '+54 minutes'), datetime(current_timestamp, '-14 days', '+8 hours', '+54 minutes')),
    (5, 'Briggs found an old diary in the woods. Not Laura’s.', '', datetime(current_timestamp, '-23 days', '+0 hours', '+37 minutes'), datetime(current_timestamp, '-23 days', '+0 hours', '+204 minutes')),
    (3, '', 'coffee-spill.jpg', datetime(current_timestamp, '-21 days', '+16 hours', '+56 minutes'), datetime(current_timestamp, '-21 days', '+16 hours', '+79 minutes')),
    (6, 'Started journaling again. Might be good for my mind.', '', datetime(current_timestamp, '-13 days', '+12 hours', '+23 minutes'), datetime(current_timestamp, '-13 days', '+12 hours', '+23 minutes')),
    (2, '', 'ambient-modules.png', datetime(current_timestamp, '-13 days', '+1 hours', '+9 minutes'), datetime(current_timestamp, '-13 days', '+1 hours', '+174 minutes')),
    (1, 'Esteban pawed my face until I woke up.', '', datetime(current_timestamp, '-10 days', '+9 hours', '+45 minutes'), datetime(current_timestamp, '-10 days', '+9 hours', '+45 minutes')),
    (4, 'Met Cooper at the diner. His eyes looked tired.', '', datetime(current_timestamp, '-20 days', '+12 hours', '+36 minutes'), datetime(current_timestamp, '-20 days', '+12 hours', '+198 minutes')),
    (5, '', 'mountain-dawn.jpg', datetime(current_timestamp, '-8 days', '+11 hours', '+48 minutes'), datetime(current_timestamp, '-8 days', '+11 hours', '+126 minutes')),
    (6, 'Thinking about going back to the Bookhouse Boys.', '', datetime(current_timestamp, '-17 days', '+7 hours', '+47 minutes'), datetime(current_timestamp, '-17 days', '+7 hours', '+140 minutes')),
    (3, 'Wind blew open the office door. No windows were open.', '', datetime(current_timestamp, '-19 days', '+21 hours', '+7 minutes'), datetime(current_timestamp, '-19 days', '+21 hours', '+7 minutes')),
    (1, '', 'sunbeam-cat.jpg', datetime(current_timestamp, '-23 days', '+18 hours', '+46 minutes'), datetime(current_timestamp, '-23 days', '+18 hours', '+46 minutes')),
    (2, 'Modular synced to heartbeat today. Don’t ask how.', '', datetime(current_timestamp, '-5 days', '+22 hours', '+43 minutes'), datetime(current_timestamp, '-5 days', '+22 hours', '+43 minutes')),
    (5, '', 'locket-drawing.jpg', datetime(current_timestamp, '-29 days', '+18 hours', '+5 minutes'), datetime(current_timestamp, '-29 days', '+18 hours', '+5 minutes')),
    (4, 'Ran into James. Still has that haunted look.', '', datetime(current_timestamp, '-26 days', '+1 hours', '+15 minutes'), datetime(current_timestamp, '-26 days', '+1 hours', '+15 minutes')),
    (1, 'Put a hat on Esteban. He hated it.', 'cat-hat.jpg', datetime(current_timestamp, '-28 days', '+19 hours', '+47 minutes'), datetime(current_timestamp, '-28 days', '+19 hours', '+47 minutes')),
    (4, 'Ran into James. Still has that haunted look.', '', datetime(current_timestamp, '-26 days', '+1 hours', '+15 minutes'), datetime(current_timestamp, '-26 days', '+1 hours', '+15 minutes')),
    (3, 'Owls again. Always watching.', '', datetime(current_timestamp, '-6 days', '+7 hours', '+23 minutes'), datetime(current_timestamp, '-6 days', '+7 hours', '+105 minutes')),
    (1, 'Put a hat on Esteban. He hated it.', 'cat-hat.jpg', datetime(current_timestamp, '-28 days', '+19 hours', '+47 minutes'), datetime(current_timestamp, '-28 days', '+19 hours', '+47 minutes')),
    (2, '', 'waveform-cave.jpg', datetime(current_timestamp, '-1 days', '+20 hours', '+38 minutes'), datetime(current_timestamp, '-1 days', '+20 hours', '+38 minutes')),
    (6, 'The clinic lights flickered at exactly 3:17am.', '', datetime(current_timestamp, '-26 days', '+13 hours', '+49 minutes'), datetime(current_timestamp, '-26 days', '+13 hours', '+49 minutes')),
    (4, '', 'audrey-staring.jpg', datetime(current_timestamp, '-9 days', '+10 hours', '+25 minutes'), datetime(current_timestamp, '-9 days', '+10 hours', '+25 minutes')),
    (3, 'Cooper left another tape in the breakroom.', '', datetime(current_timestamp, '-13 days', '+2 hours', '+47 minutes'), datetime(current_timestamp, '-13 days', '+2 hours', '+47 minutes')),
    (5, 'Heard Donna humming “Just You” again. Bittersweet.', '', datetime(current_timestamp, '-9 days', '+1 hours', '+8 minutes'), datetime(current_timestamp, '-9 days', '+1 hours', '+8 minutes')),
    (1, '', 'cat-yawn.jpg', datetime(current_timestamp, '-13 days', '+23 hours', '+21 minutes'), datetime(current_timestamp, '-13 days', '+23 hours', '+197 minutes')),
    (2, 'Set delay feedback too high. Woke up the neighbors.', '', datetime(current_timestamp, '-6 days', '+0 hours', '+25 minutes'), datetime(current_timestamp, '-6 days', '+0 hours', '+204 minutes')),
    (6, '', 'hayward-house.jpg', datetime(current_timestamp, '-1 days', '+3 hours', '+41 minutes'), datetime(current_timestamp, '-1 days', '+3 hours', '+41 minutes')),
    (4, 'Smoked behind the school again. Donna didn’t show.', '', datetime(current_timestamp, '-16 days', '+20 hours', '+25 minutes'), datetime(current_timestamp, '-16 days', '+20 hours', '+152 minutes')),
    (5, 'Dreamt of Laura, but she was speaking backwards.', '', datetime(current_timestamp, '-24 days', '+2 hours', '+43 minutes'), datetime(current_timestamp, '-24 days', '+2 hours', '+43 minutes')),
    (3, '', 'coffee-and-pie.jpg', datetime(current_timestamp, '-6 days', '+14 hours', '+19 minutes'), datetime(current_timestamp, '-6 days', '+14 hours', '+19 minutes')),
    (1, 'Esteban is hiding under the bed again.', '', datetime(current_timestamp, '-4 days', '+19 hours', '+22 minutes'), datetime(current_timestamp, '-4 days', '+19 hours', '+22 minutes')),
    (2, 'Was that you whispering near my window?', '', datetime(current_timestamp, '-15 days', '+14 hours', '+55 minutes'), datetime(current_timestamp, '-15 days', '+14 hours', '+86 minutes')),
    (6, '', 'twinpeaks-clinic-night.jpg', datetime(current_timestamp, '-13 days', '+9 hours', '+54 minutes'), datetime(current_timestamp, '-13 days', '+9 hours', '+157 minutes')),
    (4, 'Something’s not right at the Great Northern.', '', datetime(current_timestamp, '-5 days', '+19 hours', '+22 minutes'), datetime(current_timestamp, '-5 days', '+19 hours', '+155 minutes')),
    (5, 'Laura’s locket was glowing. That’s not normal.', '', datetime(current_timestamp, '-9 days', '+12 hours', '+30 minutes'), datetime(current_timestamp, '-9 days', '+12 hours', '+182 minutes')),
    (3, '', 'cooper-diary-entry.jpg', datetime(current_timestamp, '-23 days', '+23 hours', '+48 minutes'), datetime(current_timestamp, '-23 days', '+23 hours', '+213 minutes')),
    (1, 'Caught Esteban staring into the corner... again.', '', datetime(current_timestamp, '-23 days', '+21 hours', '+59 minutes'), datetime(current_timestamp, '-23 days', '+21 hours', '+62 minutes')),
    (2, '', 'oscillator-noise.jpg', datetime(current_timestamp, '-14 days', '+20 hours', '+14 minutes'), datetime(current_timestamp, '-14 days', '+20 hours', '+52 minutes')),
    (6, 'Clinic’s records are out of order. Someone tampered.', '', datetime(current_timestamp, '-5 days', '+9 hours', '+50 minutes'), datetime(current_timestamp, '-5 days', '+9 hours', '+50 minutes')),
    (4, 'Audrey walked into the Roadhouse, barefoot.', '', datetime(current_timestamp, '-8 days', '+16 hours', '+35 minutes'), datetime(current_timestamp, '-8 days', '+16 hours', '+35 minutes')),
    (5, 'Still hear her voice when I close my eyes.', '', datetime(current_timestamp, '-1 days', '+9 hours', '+31 minutes'), datetime(current_timestamp, '-1 days', '+9 hours', '+31 minutes')),
    (3, '', 'log-lady-closeup.jpg', datetime(current_timestamp, '-1 days', '+12 hours', '+36 minutes'), datetime(current_timestamp, '-1 days', '+12 hours', '+42 minutes')),
    (1, 'Why is Esteban obsessed with my modular setup?', '', datetime(current_timestamp, '-19 days', '+8 hours', '+29 minutes'), datetime(current_timestamp, '-19 days', '+8 hours', '+60 minutes')),
    (2, '', 'contact-mic.jpg', datetime(current_timestamp, '-26 days', '+6 hours', '+59 minutes'), datetime(current_timestamp, '-26 days', '+6 hours', '+186 minutes')),
    (6, 'Had a patient talk backwards. I thought I was dreaming.', '', datetime(current_timestamp, '-22 days', '+23 hours', '+55 minutes'), datetime(current_timestamp, '-22 days', '+23 hours', '+55 minutes')),
    (4, 'Found a weird key in my locker. Not mine.', '', datetime(current_timestamp, '-15 days', '+4 hours', '+32 minutes'), datetime(current_timestamp, '-15 days', '+4 hours', '+32 minutes')),
    (5, '', 'bobby-bike-again.jpg', datetime(current_timestamp, '-23 days', '+8 hours', '+22 minutes'), datetime(current_timestamp, '-23 days', '+8 hours', '+22 minutes')),
    (3, 'Sheriff’s been acting strange lately.', '', datetime(current_timestamp, '-22 days', '+0 hours', '+34 minutes'), datetime(current_timestamp, '-22 days', '+0 hours', '+156 minutes')),
    (1, '', 'esteban-attack-mode.jpg', datetime(current_timestamp, '-8 days', '+2 hours', '+34 minutes'), datetime(current_timestamp, '-8 days', '+2 hours', '+198 minutes')),
    (2, 'Field recordings picked up something not human.', '', datetime(current_timestamp, '-21 days', '+9 hours', '+16 minutes'), datetime(current_timestamp, '-21 days', '+9 hours', '+16 minutes')),
    (6, '', 'donna-at-mirror.jpg', datetime(current_timestamp, '-28 days', '+21 hours', '+44 minutes'), datetime(current_timestamp, '-28 days', '+21 hours', '+158 minutes')),
    (4, 'James said he saw Laura. That’s impossible.', '', datetime(current_timestamp, '-14 days', '+23 hours', '+15 minutes'), datetime(current_timestamp, '-14 days', '+23 hours', '+15 minutes')),
    (5, 'We buried the locket. But it’s back.', '', datetime(current_timestamp, '-13 days', '+18 hours', '+48 minutes'), datetime(current_timestamp, '-13 days', '+18 hours', '+162 minutes')),
    (3, '', 'coffee-cup-twinpeaks.jpg', datetime(current_timestamp, '-23 days', '+12 hours', '+26 minutes'), datetime(current_timestamp, '-23 days', '+12 hours', '+26 minutes')),
    (1, 'Esteban has a secret life, I’m convinced.', '', datetime(current_timestamp, '-23 days', '+19 hours', '+23 minutes'), datetime(current_timestamp, '-23 days', '+19 hours', '+58 minutes')),
    (2, '', 'feedback-loop.jpg', datetime(current_timestamp, '-12 days', '+13 hours', '+58 minutes'), datetime(current_timestamp, '-12 days', '+13 hours', '+58 minutes')),
    (6, 'Another strange light behind the clinic.', '', datetime(current_timestamp, '-11 days', '+17 hours', '+13 minutes'), datetime(current_timestamp, '-11 days', '+17 hours', '+142 minutes')),
    (4, 'Got detention for skipping. Worth it.', '', datetime(current_timestamp, '-22 days', '+13 hours', '+13 minutes'), datetime(current_timestamp, '-22 days', '+13 hours', '+13 minutes')),
    (5, 'I keep hearing the phone ring. It’s unplugged.', '', datetime(current_timestamp, '-3 days', '+5 hours', '+10 minutes'), datetime(current_timestamp, '-3 days', '+5 hours', '+10 minutes')),
    (3, '', 'tape-recorder-cooper.jpg', datetime(current_timestamp, '-9 days', '+1 hours', '+53 minutes'), datetime(current_timestamp, '-9 days', '+1 hours', '+53 minutes')),
    (1, 'Esteban slept on my synth. Again.', '', datetime(current_timestamp, '-15 days', '+21 hours', '+22 minutes'), datetime(current_timestamp, '-15 days', '+21 hours', '+136 minutes')),
    (2, '', 'whispers-wallphace.jpg', datetime(current_timestamp, '-14 days', '+23 hours', '+54 minutes'), datetime(current_timestamp, '-14 days', '+23 hours', '+155 minutes')),
    (6, 'Patient drew the Owl Cave symbol.', '', datetime(current_timestamp, '-10 days', '+3 hours', '+9 minutes'), datetime(current_timestamp, '-10 days', '+3 hours', '+9 minutes')),
    (4, 'Audrey’s dreams feel more real than life.', '', datetime(current_timestamp, '-15 days', '+13 hours', '+28 minutes'), datetime(current_timestamp, '-15 days', '+13 hours', '+150 minutes')),
    (5, '', 'grave-marker.jpg', datetime(current_timestamp, '-25 days', '+19 hours', '+6 minutes'), datetime(current_timestamp, '-25 days', '+19 hours', '+6 minutes')),
    (3, 'Cooper suspects something’s coming.', '', datetime(current_timestamp, '-2 days', '+19 hours', '+46 minutes'), datetime(current_timestamp, '-2 days', '+19 hours', '+187 minutes')),
    (1, '', 'esteban-box.jpg', datetime(current_timestamp, '-22 days', '+10 hours', '+6 minutes'), datetime(current_timestamp, '-22 days', '+10 hours', '+117 minutes')),
    (2, 'Bassline made the lights flicker.', '', datetime(current_timestamp, '-10 days', '+4 hours', '+53 minutes'), datetime(current_timestamp, '-10 days', '+4 hours', '+53 minutes')),
    (6, '', 'hayward-xray.jpg', datetime(current_timestamp, '-16 days', '+17 hours', '+41 minutes'), datetime(current_timestamp, '-16 days', '+17 hours', '+41 minutes')),
    (4, 'I think the bike trail loops when it shouldn’t.', '', datetime(current_timestamp, '-24 days', '+14 hours', '+34 minutes'), datetime(current_timestamp, '-24 days', '+14 hours', '+34 minutes')),
    (5, 'Briggs had a seizure when near the woods.', '', datetime(current_timestamp, '-5 days', '+1 hours', '+24 minutes'), datetime(current_timestamp, '-5 days', '+1 hours', '+24 minutes')),
    (3, '', 'log-lady-lantern.jpg', datetime(current_timestamp, '-11 days', '+19 hours', '+56 minutes'), datetime(current_timestamp, '-11 days', '+19 hours', '+80 minutes')),
    (1, 'My cat speaks in riddles now.', '', datetime(current_timestamp, '-21 days', '+6 hours', '+59 minutes'), datetime(current_timestamp, '-21 days', '+6 hours', '+59 minutes')),
    (2, '', 'dark-patch.jpg', datetime(current_timestamp, '-9 days', '+9 hours', '+1 minutes'), datetime(current_timestamp, '-9 days', '+9 hours', '+1 minutes')),
    (6, 'Clinic’s new patient says he’s from “the other place.”', '', datetime(current_timestamp, '-14 days', '+17 hours', '+52 minutes'), datetime(current_timestamp, '-14 days', '+17 hours', '+118 minutes')),
    (4, 'Bobby’s bike was upside down outside the diner.', '', datetime(current_timestamp, '-29 days', '+12 hours', '+22 minutes'), datetime(current_timestamp, '-29 days', '+12 hours', '+200 minutes'));

INSERT INTO UserFollows (follower_id, followee_id)
VALUES 
    (7, 1),
    (7, 2),
    (7, 3),
    (7, 4),
    (7, 5),
    (7, 6);
