name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: action/checkout@v3

      - name: Set up go
        uses: action/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Run tests
        run: go test ./...
